### ISSUE TITLE
MSP430 Toolchain does not work on Windows

### ISSUE THREAD

**Issue by ivankravets** [platformio/platform-timsp430#2]
# Moved from https://github.com/platformio/platformio/issues/493

/cc @nmaas87

------

I did try to compile the Blink project example with the most recent version of Platformio in Atom.io in Windows 8.1 64 bit but got the problem that the Toolchain does not work for MSP430:
Error was

My User.platformio\packages\ldscripts" -L.pioenvs\lpmsp430g2553 -Wl,--start-group -lm .pioenvs\lpmsp430g2553\libFrameworkEnergia.a -Wl,--end-group
c:/users/My User/.platformio/packages/toolchain-timsp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld.exe: cannot open linker script file memory.x: No such file or directory
collect2: ld returned 1 exit status
scons: **\* [.pioenvs\lpmsp430g2553\firmware.elf] Error 1
 [ ERROR ] Took 2.63 seconds 

Any idea how to solve that?

**Comment by ivankravets** [comment]
@nmaas87 could you try new development version? It should work

**Comment by ivankravets** [comment]
It looks that it works. See https://ci.appveyor.com/project/ivankravets/platform-timsp430

Please reopen this issue if you still have any problems

**Comment by nmaas87** [comment]
It works, I just did try it :)!
