### ISSUE TITLE
Add TI MSP430FR5994

### ISSUE THREAD

**Issue by dcomer** [platformio/platform-timsp430#33]
Can the TI MSP430FR5994 be added? I'm looking at using that launchpad with the Audio Signal Processing BoosterPack.
Thank You.

**Comment by valeros** [comment]
Hi @dcomer, isn't this board already available https://docs.platformio.org/en/latest/boards/timsp430/lpmsp430fr5994.html ?

**Comment by dcomer** [comment]
My apologies. Thanks for pointing that out to me.
