### ISSUE TITLE
TI MSP-EXP430FR2433

### ISSUE THREAD

**Issue by shaunhey** [platformio/platform-timsp430#8]
Please add support for the newest TI MSP430 Launchpad, the TI MSP-EXP430FR2433. Support for this board was recently added to TI's Arduino fork, Energia.

http://www.ti.com/tool/msp-exp430fr2433

Output of ```pio device list```:
```
/dev/ttyACM1
------------
Hardware ID: USB VID:PID=2047:0013 SER=58349B6F0F000C00 LOCATION=1-1.1.3:1.2
Description: MSP Tools Driver - MSP Application UART

/dev/ttyACM0
------------
Hardware ID: USB VID:PID=2047:0013 SER=58349B6F0F000C00 LOCATION=1-1.1.3:1.0
Description: MSP Tools Driver - MSP Debug Interface
```

**Comment by ngmacha** [comment]
I second this request too! But looks like nobody is working on this?...

**Comment by profra** [comment]
MSP430FR2433 ... please, do not wait and start the implementation ... TI has done a lot of support actions  for this chip.... e.g. launchpad for USD 4.30... it would be nice to have the right tool in the PIO

**Comment by profra** [comment]
It would be nice to know... WHEN if YES or WHY if NOT... FR2433 is a nice piece of HW for LP apps!!!

**Comment by almorsousa** [comment]
any news on this ?

**Comment by profra** [comment]
It seems that "the city of MSP430 from the land PLATFORM.IO" has completely died out ... That's a great shame!

**Comment by PRO2XY** [comment]
Is there any guide on how to port Arduino / Energia implementation to PlatformIO?
